### ISSUE TITLE
Handle connection issues better in LS elasticsearch input

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/logstash#1634]
I have ES running on a different port than the default (9200) but have not defined a port parameter explicitly in the configuration, the result is the following:
```
  Error: undefined method `bytesize' for nil:NilClass
  Exception: NoMethodError
  Stack: /Users/<user_name>/ELK/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/http/message.rb:65:in `body='
/Users/<user_name>/ELK/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:298:in `request'
/Users/<user_name>/ELK/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:217:in `post!'
/Users/<user_name>/ELK/logstash-1.4.1/lib/logstash/inputs/elasticsearch.rb:95:in `run'
/Users/<user_name>/ELK/logstash-1.4.1/lib/logstash/pipeline.rb:163:in `inputworker'
/Users/<user_name>/ELK/logstash-1.4.1/lib/logstash/pipeline.rb:157:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"168"}
```
Which is a confusing error.  This can certainly be addressed by specifying a port parameter for the non-standard port.  Would be nice for the plugin to throw a more intuitive error message though :)

**Comment by untergeek** [comment]
Migrated to https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/8
