### ISSUE TITLE
workers > 1 - S3 output plugin - no such file or directory

### ISSUE THREAD

**Issue by vjanelle** [elasticsearch/logstash#1915]
@ph @electrical more review from my testings

Refers to PR #1913 

```
Errno::ENOENT: No such file or directory - /opt/logstash/S3_temp/ls.s3.XXX.2014-10-17T21.00.tag_all.part0.txt
                       unlink at org/jruby/RubyFile.java:1093
          move_file_to_bucket at /opt/logstash/lib/logstash/outputs/s3.rb:226
  configure_periodic_uploader at /opt/logstash/lib/logstash/outputs/s3.rb:238
                   time_alert at /opt/logstash/lib/logstash/outputs/s3.rb:139
                         loop at org/jruby/RubyKernel.java:1501
                   time_alert at /opt/logstash/lib/logstash/outputs/s3.rb:137
syslog udp listener died {:address=>"0.0.0.0:5554", :exception=>#<SocketError: recvfrom: name or service not known>, :backtrace=>["/opt/logstash/lib/logstash/inputs/syslog.rb:120:in `udp_listener'", "org/jruby/RubyKernel.java:1501:in `loop'", "/opt/logstash/lib/logstash/inputs/syslog.rb:119:in `udp_listener'", "/opt/logstash/lib/logstash/inputs/syslog.rb:77:in `run'"], :level=>:warn}
```

```
input {
  sqs {
    queue => "logstash-beaver"
    region => "eu-west-1"
    threads => 4
    tags => ['all','sqs']
  }
  tcp {
    port => 5000
    codec => json_lines
    tags => ['all','tcp5k']
  }
  syslog {
    type => syslog
    port => 5554
    tags => ['all','syslog']
  }
}

output {
stdout {}
  elasticsearch_http {
    host => "logstash-es"
    port => "9200"
    workers => 4
    tags => ['all']
 }
 s3 {
endpoint_region => "eu-west-1"
  bucket => "logstash-archive-eu-west-1"
  tags => ['all']
  time_file => 1
  workers => 2
 }
}
```

It appears the file exists:
```
logstash@:/opt/logstash/S3_temp$ ls ls.s3.XXX.2014-10-17T21.00.tag_all.part0.txt
ls.s3.XXX.2014-10-17T21.00.tag_all.part0.txt
```

**Comment by ph** [comment]
This is fixed in the latest version of the plugin in https://github.com/logstash-plugins/logstash-output-s3/
Will be released with 1.5.
