### ISSUE TITLE
Metrics filter breaks logstash rspec tests

### ISSUE THREAD

**Issue by Crazybus** [elasticsearch/logstash#2125]
Adding metrics to the filters section causes rspec tests to fail with `TypeError: can't convert String into Integer`. As a workaround I have just moved my metrics to a seperate conf file in my conf.d directory. Configtest passes and everything works perfectly...only the rspec tests are failing. Is this expected behaviour? 

Works:
```
# encoding: utf-8

require "test_utils"

describe "Metrics breaks logstash rspec tests", :if => RUBY_ENGINE == "jruby" do
  extend LogStash::RSpec
  config <<-CONFIG
filter { 
}
CONFIG
  sample("message" => "test") do
    subject["message"].should eql("test")
  end 
end
```

Breaks:
```
# encoding: utf-8

require "test_utils"

describe "Metrics breaks logstash rspec tests", :if => RUBY_ENGINE == "jruby" do
  extend LogStash::RSpec
  config <<-CONFIG
filter { 
  metrics {
    meter => "events"
    add_tag => "metric"
  }
}
CONFIG
  sample("message" => "test") do
    subject["message"].should eql("test")
  end 
end
```

Error:
```
logstash rspec test.rb
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true, :broken=>true, :export_cypher=>true}
F

Failures:

  1) Metrics breaks logstash rspec tests "{"message":"test"}" when processed
     Failure/Error: Unable to find matching line from backtrace
     TypeError:
       can't convert String into Integer
     # ./test.rb:16:in `(root)'
     # /opt/logstash/lib/logstash/runner.rb:58:in `run'
     # /opt/logstash/lib/logstash/runner.rb:136:in `run'
     # /opt/logstash/lib/logstash/runner.rb:175:in `run'
     # /opt/logstash/lib/logstash/runner.rb:92:in `main'
     # /opt/logstash/lib/logstash/runner.rb:215:in `(root)'

Finished in 1.92 seconds
1 example, 1 failure

Failed examples:

rspec /opt/logstash/spec/test_utils.rb:109 # Metrics breaks logstash rspec tests "{"message":"test"}" when processed
```

**Comment by jsvd** [comment]
The testing dsl has since changed a bit and tests have been added to the metrics filter https://github.com/logstash-plugins/logstash-filter-metrics/blob/master/spec/filters/metrics_spec.rb
Closing issue, let us know if there's still a problem w/ this

**Comment by bharath-rajakumar** [comment]
@jsvd Could you provide an example spec file for testing a logstash conf file that has the metrics filter?
I had experience the same problem as @Crazybus did.
