### ISSUE TITLE
logstash Error

### ISSUE THREAD

**Issue by versnel** [elasticsearch/logstash#2153]
Hallo there,

I'm getting the following error in the log file of Logstash when kibana is trying to open/connect with Elasticsearch. And for Kibana I get a blank page.

adim@Suricata:~# tail -f /var/log/logstash/logstash.log
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:680)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:643)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:610)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:133)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
log4j, [2014-12-01T21:32:11.551]  WARN: org.elasticsearch.transport.netty: [logstash-Suricata-21556-4012] exception caught on transport layer [[id: 0x95f6a5cf]], closing connection
java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:127)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:644)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:634)
        at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:680)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:643)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:610)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:133)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
log4j, [2014-12-01T21:32:13.482]  WARN: org.elasticsearch.monitor.jvm: [Fan Boy] [gc][young][324][691] duration [1.3s], collections [1]/[2.6s], total [1.3s]/[4.7m], memory [78.8mb]->[77.3mb]/[491.6mb], all_pools {[young] [1.8mb]->[68.2kb]/[66.5mb]}{[survivor] [325.6kb]->[402.7kb]/[8.3mb]}{[old] [76.7mb]->[76.9mb]/[416.8mb]}

The version that i'm using is:

- Logstash_1.4.2-1-2c0f5a1_all
- Kibana 3.1.2
- Elasticsearch 1.4.0

Plz help

**Comment by versnel** [comment]
Hi Suyograo

No still no luck.

This is what i'm getting:

log4j, [2015-01-09T00:10:20.067]  WARN: org.elasticsearch.transport.netty: [logstash-Suricata-1542-4014] exception caught on transport layer [[id: 0x5ec9ec39]], closing connection
java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:123)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:634)
        at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:680)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:643)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:610)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:133)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pjanzen** [comment]
Hi versnel,

can you post you logstash config and you kinana config.js?

Paul.

**Comment by versnel** [comment]
-----Logstash-----

input {
  file {
    path => ["/root/test/test/eve.json"]
    codec =>   json
    type => "SuricataIDPS-logs"
    start_position => "beginning"
  }

}

filter {
  if [type] == "SuricataIDPS-logs" {
    date {
      match => [ "timestamp", "ISO8601" ]
    }
  }

  if [src_ip]  {
    geoip {
      source => "src_ip"
      target => "geoip"
      database => "/opt/logstash/vendor/geoip/GeoLiteCity.dat"
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float" ]
    }
  }
}

output {
  elasticsearch {
    host => "localhost:9200"
    embedded => true
  }
}

**Comment by versnel** [comment]
----Kibana-----

/** @scratch /configuration/config.js/1
 *
 * == Configuration
 * config.js is where you will find the core Kibana configuration. This file contains parameter that
 * must be set before kibana is run for the first time.
 */
define(['settings'],
function (Settings) {


  /** @scratch /configuration/config.js/2
   *
   * === Parameters
   */
  return new Settings({

    /** @scratch /configuration/config.js/5
     *
     * ==== elasticsearch
     *
     * The URL to your elasticsearch server. You almost certainly don't
     * want +http://localhost:9200+ here. Even if Kibana and Elasticsearch are on
     * the same host. By default this will attempt to reach ES at the same host you have
     * kibana installed on. You probably want to set it to the FQDN of your
     * elasticsearch host
     *
     * Note: this can also be an object if you want to pass options to the http client. For example:
     *
     *  +elasticsearch: {server: "http://localhost:9200", withCredentials: true}+
     *
     */
    elasticsearch: "http://"+window.location.hostname+":9200",

    /** @scratch /configuration/config.js/5
     *
     * ==== default_route
     *
     * This is the default landing page when you don't specify a dashboard to load. You can specify
     * files, scripts or saved dashboards here. For example, if you had saved a dashboard called
     * `WebLogs' to elasticsearch you might use:
     *
     * default_route: '/dashboard/elasticsearch/WebLogs',
     */
    default_route     : '/dashboard/file/default.json',

    /** @scratch /configuration/config.js/5
     *
     * ==== kibana-int
     *
     * The default ES index to use for storing Kibana specific object
     * such as stored dashboards
     */
    kibana_index: "kibana-int",

    /** @scratch /configuration/config.js/5
     *
     * ==== panel_name
     *
     * An array of panel modules available. Panels will only be loaded when they are defined in the
     * dashboard, but this list is used in the "add panel" interface.
     */
    panel_names: [
      'histogram',
      'map',
      'goal',
      'table',
      'filtering',
      'timepicker',
      'text',
      'hits',
      'column',
      'trends',
      'bettermap',
      'query',
      'terms',
      'stats',
      'sparklines'
    ]
  });
});

**Comment by pjanzen** [comment]
Whats happens if you replace this
"http://"+window.location.hostname+":9200"
with this
"http://the.actual.fqdn.or.ip.of.your.elasticsearch.server:9200"

**Comment by versnel** [comment]
No luck same error msg:

log4j, [2015-01-09T14:34:39.351]  WARN: org.elasticsearch.transport.netty: [logstash-Suricata-16307-4016] exception caught on transport layer [[id: 0xb2ed996f]], closing connection
java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:123)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:634)
        at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:680)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:643)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:610)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:133)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

And in the Kibana webinterface this msg:
No results - There were no results because no indices were found that match your selected time span

**Comment by versnel** [comment]
I change it as you sad.

elasticsearch: "http://MY-PUBLIC-IP:9200",

**Comment by versnel** [comment]
![image](https://cloud.githubusercontent.com/assets/9933976/5681271/702c4468-97ed-11e4-9a21-f558e4678f4c.png)

**Comment by versnel** [comment]
![image](https://cloud.githubusercontent.com/assets/9933976/5681437/fae9f950-97ee-11e4-9326-ccb2041f6e88.png)

**Comment by pjanzen** [comment]
Looks like you getting there, in elasticsearch you have a index right? configure that in kibana and you should have some data shown.

**Comment by pjanzen** [comment]
but you do not have any data in ES...

[pjanzen@macpro ~]$ curl -XGET http://191.233.65.106:9200/_aliases?pretty=1
{
  "kibana-int" : { }
}

You also might want to configure a firewall.

**Comment by versnel** [comment]
I don't get it... What do i have to change in ES index section and then config in Kibana?

On working a cloud computer on Microsoft Azure. What you mean with config a firewall?

**Comment by pjanzen** [comment]
Your elasticsearch and logstash host is reachable for anyone who has the ip info.

In order to show data in kibana you have to have data in elasticsearch this is something you have not. or atleast I cannot see it.

**Comment by versnel** [comment]
I'm sorry i'm asking a lot of question but i'm new to all this. 
I now understand the problem, but the question is how do i send data to elasticsearch?

**Comment by pjanzen** [comment]
That is a totaly differnt question :) google for some simple examples like apache2 access files and start there, also if you are helped with this question please close it and after some research open a new question.

Good luck
Paul.

**Comment by versnel** [comment]
Pjanzen maybe some help again.

These are the 2 3 error's im getting.

Elasticsearch log:
[2015-01-22 16:41:40,609][DEBUG][action.search.type ] [suricata] All shards failed for phase: [query]
[2015-01-22 16:55:02,899][INFO ][cluster.service ] [suricata] added {[logstash-Suricata-8947-4016][HTvXM0AQR6mqKmeQf0Cn0g][Suricata][inet[/LOCAL_IP:9301]]{data=false, client=true},}, reason: zen-disco-receive(join from node[[logstash-Suricata-8947-4016][HTvXM0AQR6mqKmeQf0Cn0g][Suricata][inet[/LOCAL_IP:9301]]{data=false, client=true}])

Logstash Log:
WARN: org.elasticsearch.discovery.zen: [logstash-Suricata-8947-4016] master_left and no other node elected to become master, current nodes: {[logstash-Suricata-8947-4016][HTvXM0AQR6mqKmeQf0Cn0g][Suricata][inet[/LOCAL_IP:9301]]{data=false, client=true},}
