### ISSUE TITLE
NOOP tests are randomly failing

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#2353]
Finished in 2.91 seconds
229 examples, 25 failures

Failed examples:

[....]
25) LogStash::Filters::NOOP remove_tag "{"type":"noop","tags":["t1","t2"]}" when processed
     Failure/Error: let(:pipeline) { LogStash::Pipeline.new(config) }
     Gem::LoadError:
       Could not find 'logstash-filter-noop' (>= 0) among 70 total gem(s)
     # ./lib/logstash/config/mixin.rb:214:in `plugin_version'
     # ./lib/logstash/config/mixin.rb:227:in `print_version_notice'
     # ./lib/logstash/config/mixin.rb:204:in `validate'
     # ./lib/logstash/config/mixin.rb:100:in `config_init'
     # ./lib/logstash/filters/base.rb:134:in `initialize'
     # ./lib/logstash/pipeline.rb:268:in `plugin'
     # (eval):7:in `initialize'
     # ./lib/logstash/pipeline.rb:32:in `initialize'
     # ./spec/filters/base_spec.rb:173:in `(root)'
     # ./spec/filters/base_spec.rb:173:in `(root)'
     # ./lib/logstash/runner.rb:58:in `run'
     # ./lib/logstash/runner.rb:113:in `run'
     # ./lib/logstash/runner.rb:171:in `run'

Randomized with seed 16474
````

**Comment by ph** [comment]
Seem to only be present in #2331
