### ISSUE TITLE
Support for draft-ietf-json-text-sequence

### ISSUE THREAD

**Issue by wsanchez** [elasticsearch/logstash#2381]
logstash should ingest JSON data in this form: https://datatracker.ietf.org/doc/draft-ietf-json-text-sequence/

Basically, that means `RS + JSON + LF`.

Since log stash already handles `JSON + LF`, a trivial parser could simply delete the leading RS character.  A smarter one would use this to detect truncated JSON text and recover the following record, as described in the spec.

**Comment by jordansissel** [comment]
> a trivial parser could simply delete

This draft defines the JSON part as : 
* possible-JSON = 1*(not-RS);
* not-RS = %x00-1d / %x1f-ff; any octets other than RS

Except the RS character 0x1E appears to be accepted by the Ruby and Python JSON parsers, where as this RFC requires we reject this RS within the JSON octets. So simply trimming the RS, or splitting a stream on RS, seems like not the correct approach to solving it.

I confess I haven't read the complete rfc, but the grammar alone was conflict enough to cause me to stop reading for now. My specific concerns on this rfc draft are not necessary in the context of this ticket :)

---

Two questions:
* Have you actually seen this format in the wild? What program(s) or device(s) emit it?
* e have `json_lines` as a codec now, and we could improve this codec and make the separator configurable which would allow you to use a \xE1 as the separator instead of \n. Thoughts?

**Comment by jordansissel** [comment]
For additional data point: Because I had not seen any evidence of its use, I didn't care to support RFC5424 (an alternative syslog message format) even though it's been around for a long time. Once I became aware that users were seeing this format in the wild, I grew interest in supporting it :)

So!

There are two options here:
1) We support this, somehow, in the json_lines codec. This is pending time and energy, but if given sufficient evidence of its use, we can direct energy at it :)
2) You, or someone else, provides a separate codec specific to this json enveloping format.

**Comment by wsanchez** [comment]
Well, I'm writing code to emit logs in this form, but one objection I got was that log stash doesn't support it.  :-)

**Comment by glyph** [comment]
> the RS character 0x1E appears to be accepted by the Ruby and Python JSON parsers

Python's, at least, seems to not accept it:

```
>>> import json
>>> json.loads('\x1E{}')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File ".../json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>> 
```

**Comment by jordansissel** [comment]
> Python's, at least, seems to not accept it:

What I Meant was that RS was accepted in string values in Ruby and Python. 

However, upon further study, I see I had a typo and \u00E1 is actually invalid (expectedly) in a json string.

This said, we can probably solve this by adding a customizeable json stream separator in the json_lines codec (split on \xE1 instead of \n)

**Comment by glyph** [comment]
@jordansissel This would have the advantage of allowing logs with pretty-printed JSON objects, whereas newline-separated ones require weird pseudo-canonicalization to get rid of whitespace.

**Comment by wsanchez** [comment]
A switch to this form can be done automatically, insofar as the first character in the stream is RS.

**Comment by jordansissel** [comment]
> This would have the advantage

I'm not arguing for or against this RS-delimited strategy (this isn't the right forum, either, for such a discussion). I'm mostly wondering about the impact of attempting to do this RS delimiting by default - I am not sure about making a default behavior support a framing strategy that I've never actually seen and whose proposal is only a few months old.

**Comment by jordansissel** [comment]
Is there still interest in this?

**Comment by glyph** [comment]
I'd definitely love to see it, as it would be at least a formal standard to comply with.

**Comment by wsanchez** [comment]
I'm interested, because I do think it's a more reliable format and adoption by logstash would enable broader use.

**Comment by wsanchez** [comment]
And FWIW, it's no longer a draft but an actual RFC.  (Glyph alluded to this above, but in case anyone's worried about it still changing.)

**Comment by jordansissel** [comment]
For my own prioritization, I'm not sure how to rank it -- I've never seen this format in the wild, so it's personally low on the list of things todo.

Happy to help review or guide patches through though. Let me know :)

If anyone's interested, this would probably be best done as a codec in today's Logstash.

**Comment by guyboertje** [comment]
The RFC talks about parsers implementing this. But we should not rely on parsers.

According to the rfc the first character is a RS and the last a LF with LFRS separating the JSON.

This is a begin end multiline pattern.  The new FSM based multiline implementation proposed to be shared by Filebeat and LS will mean instant support for this.

**Comment by jordansissel** [comment]
@guyboertje the way I read the RFC, is that only a subset of JSON is valid (strings with \x1E are not allowed, for example, in this rfc, but are valid in JSON). Further, LF is valid in JSON as whitespace. Also, based on my reading of the RFC, multiple RS can follow eachother, so you could have `RS{ "some": "json" }LFRSRSRSRSRS{ "more": "json" }LF` - and that multiple RS-only sequences are things to ignore, so I'm not sure it fits exactly with our start/end patterns for multiline today. The RFC also specifies a number of things about validating the JSON and dropping invalid JSON that are counter to what we do today when JSON parse failures occur. I have no strong conclusion here, but adding this as a new codec (and later moving it to be a mill) is fine with me.

**Comment by glyph** [comment]
@jordansissel -

> strings with \x1E are not allowed, for example, in this rfc, but are valid in JSON

This is incorrect.  RS is not allowed in JSON at all.  Quoting http://rfc7159.net/rfc7159#rfc.section.7:

> All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, *and the control characters (U+0000 through U+001F)*.

(emphasis mine)

This is the standard.  But what about implementations?  They all reject it:

node.js:
```javascript
> JSON.parse('{"x": "\x1e"}')
SyntaxError: Unexpected token 
    at Object.parse (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

Python:

```python
>>> import json
>>> json.loads('{"x": "\x1e"}')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/
lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/
lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/
lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8 (char 7)
```

Ruby:

```ruby
irb(main):009:0> JSON.parse "{\"x\": \"\x1E\"}"
JSON::ParserError: 784: unexpected token at '{"x": ""}'
	from /Users/glyph/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/glyph/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from (irb):9
	from /Users/glyph/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

In conclusion: LF is valid in JSON as whitespace but RS isn't.  If you use a control character in JSON, you can only use it in a string, and you have to escape it if you do.

**Comment by jordansissel** [comment]
@glyph I ran experiments yesterday that showed contradictory results to yours, but I may have made typos or other mistakes in them. Either way, I have no personal interest in this RFC. The best way to implement this is with a codec in Logstash, and you don't need my support for this :)

**Comment by glyph** [comment]
@jordansissel Sadly, I barely know ruby well enough to write that `JSON.parse` line, so unless I get a lot of free time soon, I will have to convince someone else that it's worthwhile :).  I just wanted to make sure that whoever reads this thread has accurate information.

**Comment by guyboertje** [comment]
@glyph - I believe your encoding is wrong. `"\x1E"` is not valid in a JSON String, but `"\u001E"` is.

```sh
> h = JSON.load '{"x": "\u001E"}'
=> {"x"=>"\u001E"}
> h['x'].size
=> 1
```
Also, the RFC does not support pretty printed JSON because any `LF`s in the JSON object would prematurely terminate the JSON. If we relaxed the spec and only paid attention to the `RS` character then pretty printed JSON would be ingestable.

@jordansissel - The Event Mill concept should incorporate a `byte to text chunk FSM` and a `text chunk to text chunks FSM` for event data boundary detection. With begin and end or begin or end support in both FSMs. For example, for this RFC, in the `byte to text chunk FSM`, `RS` would be the begin byte and `LF` the end byte.

**Comment by glyph** [comment]
@guyboertje 

> @glyph - I believe your encoding is wrong. "\x1E" is not valid in a JSON String, but "\u001E" is.
> 
> > h = JSON.load '{"x": "\u001E"}'
> => {"x"=>"\u001E"}
> > h['x'].size
> => 1

This has nothing to do with encodings, nor with \x1e vs. \u001e; these are both the same unicode code point.  By using single-quotes, you are disabling unicode escapes, so the literal code points that JSON is parsing is in fact "backslash, u, zero, zero, one, e", as opposed to "record separator".  Observe:

```ruby
irb(main):001:0> '\u001e'
=> "\\u001e"
irb(main):002:0> '\x1e'
=> "\\x1e"
irb(main):003:0> "\u001e"
=> "\u001E"
irb(main):004:0> "\x1e"
=> "\u001E"
```

> Also, the RFC does not support pretty printed JSON because any LFs in the JSON object would prematurely terminate the JSON. If we relaxed the spec and only paid attention to the RS character then pretty printed JSON would be ingestable.

JSON can be pretty-printed with CRs (and in fact most pretty-printers I'm aware of do just that) without using LFs at all.

You don't really need to relax the spec much, though, if you are concerned about literal LFs; you could still ensure the separator is LF/RS but just ignore LFs *not* paired with an RS (while still erroring on an RS not paired with an LF).

**Comment by guyboertje** [comment]
@glyph - Look again, `h['x'].size` is 1 not 6.
From the JSON spec, `\x1e` is not legal in JSON Strings.
The issue here is not what the Ruby interpreter 'sees' in single or double quotes - it is what the JSON parser 'sees' as it tokenizes the character sequence `"\x1e"` or `"\u001e"`.

**Comment by glyph** [comment]
> @glyph - Look again, h['x'].size is 1 not 6.

Yes, I understand that.

> From the JSON spec, \x1e is not legal in JSON Strings.

Let's be precise.

From the JSON spec, a JSON *string* may contain the code point U+001E, but in the *input* to a compliant JSON parser, the code point U+001E may not appear; if it occurs in a string being serialized as JSON, it must be escaped via the JSON escaping mechanism, i.e. it must be represented within double quotes as `\u001e`, e.g. U+005E U+0075 U+0030 U+0030 U+0031 U+0065.

> The issue here is not what the Ruby interpreter 'sees' in single or double quotes - it is what the JSON parser 'sees' as it tokenizes the character sequence "\x1e" or "\u001e".

In my earlier example, I was demonstrating that the code point U+001E is illegal in the context of JSON input (it needs to be escaped).  You suggested that my "encoding was wrong", and that I needed to use \u001e rather than \x1e.  But, since I was using double-quoted ruby strings, \x1e was shorthand for U+001E.  I can switch to a \u escape sequence and there's no difference in the error:

```ruby
irb(main):001:0> require("JSON")
=> true
irb(main):002:0> JSON.parse "{\"x\": \"\u001e\"}"
JSON::ParserError: 784: unexpected token at '{"x": ""}'
	from /Users/glyph/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/glyph/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from (irb):2
	from /Users/glyph/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):003:0> 
```

So I am providing neither the character sequence "\\" "x" "1" "e" nor the character sequence "\\" "u" "0" "0" "1" "e" in either of these cases; in both, I am providing just the code point "\u001e".

The point here is that we do not worry about U+001E being featured as valid whitespace in input, or relaxing any delimiting rules in the specification to allow it to appear; it will be rejected by all commonly-used parsers and by the spec.

**Comment by guyboertje** [comment]
My apologies, I stand corrected regarding the embedding of the actual `RS` character anywhere in the JSON input - it is invalid to do so.

In terms of pretty printing and `CR` - Jackson, the JSON processor that we use in LS, uses `LF` in pretty printed output. It is moot though, because we can't expect that the input we receive from has been crafted using Jackson.

We are developing a more advanced mechanism to extract chunks of LS Event input from blocks of text though. This mechanism will be able to extract the JSON snippets from a stream that is formatted according to this RFC.

**Comment by jordansissel** [comment]
For simplicity, I wonder if this proposal would be best done as a new codec instead of modifying existing code.
