### ISSUE TITLE
elasticsearch output doesn't restart after failure

### ISSUE THREAD

**Issue by drewr** [elasticsearch/logstash#2516]
We have a couple of web frontends that have stopped reporting logs.  The last note in the logstash log mentions a manticore failure talking to elasticsearch, and then nothing else.

https://gist.github.com/drewr/0ef6a4ca02c32131400c

```
@4000000054d000910a9ff2a4 {:timestamp=>"2015-02-02T22:56:07.177000+0000", :message=>"Got error to send bulk of actions to elasticsearch server at es00 : Manticore::Timeout", :level=>:error}
@4000000054d000910aa8eb84 {:timestamp=>"2015-02-02T22:56:07.178000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>682, :exception=>#<Manticore::Timeout: Manticore::Timeout>, :backtrace=>["/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/manticore-0.3.2-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/manticore-0.3.2-java/lib/manticore/response.rb:61:in `call'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/manticore-0.3.2-java/lib/manticore/response.rb:215:in `call_once'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/manticore-0.3.2-java/lib/manticore/response.rb:127:in `code'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/manticore.rb:50:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch/protocol.rb:82:in `bulk'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:444:in `flush'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:442:in `flush'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:216:in `buffer_flush'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:193:in `buffer_flush'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1501:in `loop'", "/usr/local/logstash/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

Our config looks a bit like this:

```
input {
  file {
    codec => json
    path => "<%= @cfg["path"]  %>"
  }
}

filter {
  mutate {
    gsub => ["time", " [^ ]+$", ""]
  }

  ruby {
    code => "event['last_origin'] = event['origin'].split(', ').last if event['origin'] and event['origin'] != '-'"
  }

  # Process only valid IPv4 addresses (sometimes IPv6 sneaks in and breaks
  # both logstash and elasticsearch)
  if [last_origin] =~ /^(\d{1,3}\.){3}\d{1,3}$/ {
    geoip {
      source => "last_origin"
      target => "geo"
    }
  } else {
    mutate {
      rename => [ "last_origin", "last_origin_ipv6" ]
    }
  }

  download_stats {
  }

  date {
    # eg "2014-11-03T23:00:03+00:00"
    match => ["time", "YYYY-MM-dd'T'HH:mm:ssZ", "YYYY-MM-dd'T'HH:mm:ss"]
  }
}

output {
  #stdout { codec => rubydebug }
  #stdout { codec => dots }

  elasticsearch {
    protocol => "http"
    host => "<%= @cfg["elasticsearch_host"] %>"
    port => "<%= @cfg["elasticsearch_port"] %>"
    index => "<%= @cfg["index"] %>"
    index_type => "log"
  }
}
```

**Comment by untergeek** [comment]
That's kind of deceptive calling it `elasticsearch_http` in the title, then using `protocol => "http"` in your elasticsearch block :wink: 

I was going to say that `elasticsearch_http` is deprecated...

**Comment by untergeek** [comment]
Is this with 1.5 or 1.4.2?

**Comment by untergeek** [comment]
There's new retry logic in 1.5's most recent plugin version, that's why I mention it.

**Comment by drewr** [comment]
@untergeek Whoops, no deception intended.  Thought `elasticsearch_http` was what happened under the hood.  Didn't realize the same plugin did node client and http.

It's 1.5, but according to @talevy the new retry logic is just about individual doc failures and not transport issues.

**Comment by jordansissel** [comment]
@drewr yeah, transport issues should result in a full retry (looping if it keeps failing). We should try to simulate this failure and see if we can reproduce it with a test case.

**Comment by talevy** [comment]
@drewr tentative fix, adding integration test to ensure this

https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/49

It was indeed a bug. no exception was raised (only logged) so Stud::Buffer did not go into it's infinite retry plan

**Comment by talevy** [comment]
closed via: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/49
