### ISSUE TITLE
rake test broken

### ISSUE THREAD

**Issue by joekiller** [elasticsearch/logstash#2688]
After running `rake bootstrap` off master I then try to run `rake test` and get the following:

```
$ rake test
rake aborted!
no such file to load -- rspec/core/runner
org/jruby/RubyKernel.java:1071:in `require'
/Users/pub/logstash/rakelib/test.rake:5:in `run_rspec'
/Users/pub/logstash/rakelib/test.rake:11:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test => test:core
(See full trace by running task with --trace)
```

Here is the full trace:
```
$ rake test --trace
** Invoke vendor:jruby (first_time)
** Execute vendor:jruby
** Invoke vendor/_/jruby-bin-1.7.17.tar.gz (first_time)
** Invoke vendor/_ (first_time, not_needed)
** Invoke vendor (first_time, not_needed)
** Execute vendor/_/jruby-bin-1.7.17.tar.gz
** Invoke vendor/jruby (first_time, not_needed)
** Invoke vendor (not_needed)
** Invoke dependency:archive-tar-minitar (first_time)
** Execute dependency:archive-tar-minitar
** Invoke gem:require (first_time)
** Execute gem:require
** Invoke vendor:jruby-patch (first_time)
** Execute vendor:jruby-patch
** Invoke test (first_time)
** Invoke test:core (first_time)
** Execute test:core
rake aborted!
no such file to load -- rspec/core/runner
org/jruby/RubyKernel.java:1071:in `require'
/Users/pub/logstash/rakelib/test.rake:5:in `run_rspec'
/Users/pub/logstash/rakelib/test.rake:11:in `(root)'
org/jruby/RubyProc.java:271:in `call'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:236:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:231:in `execute'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:175:in `invoke_with_call_chain'
/Users/pub/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:168:in `invoke_with_call_chain'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:197:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:195:in `invoke_prerequisites'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:174:in `invoke_with_call_chain'
/Users/pub/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:168:in `invoke_with_call_chain'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/task.rb:161:in `invoke'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:149:in `invoke_task'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:106:in `top_level'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:115:in `run_with_threads'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:100:in `top_level'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:78:in `run'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:165:in `standard_exception_handling'
/Users/pub/logstash/vendor/jruby/lib/ruby/shared/rake/application.rb:75:in `run'
/Users/pub/logstash/vendor/jruby/lib/ruby/gems/shared/gems/rake-10.1.0/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
vendor/jruby/bin/rake:23:in `(root)'
Tasks: TOP => test => test:core
```

**Comment by ph** [comment]
The `rake bootstrap` is misleading in this case, since it only bootstrap the jruby environment but doesn't install the dev dependencies. I have updated the doc with the `rake test:install-core`, this command will correctly setup the minimal dev environment needed to run `rake test`
