### ISSUE TITLE
geoip filter errors using rpm build of Logstash 1.5

### ISSUE THREAD

**Issue by kurtado** [elasticsearch/logstash#2723]
After installing version 1.5 via RPM using both my build and @suyograo's, the geoip filter did not run and logstash exited. Looks like an issue with LS not being able to find the MaxMind DB file. 

To recreate, on a fresh RHEL7 install (also fedora21 and centos7):

```
curl -O https://s3.amazonaws.com/users.elasticsearch.org/suyog/logstash-patch/logstash-1.5.0.beta2-1.noarch.rpm
yum -y install java
rpm -ivh logstash-1.5.0.beta2-1.noarch.rpm
```
A smoke test will run successfully:
```
/opt/logstash/bin/logstash -e 'input {stdin{}} output {stdout{codec=>rubydebug}}'
```
But using the geoip filter fails:
```
/opt/logstash/bin/logstash --debug -e 'input {stdin{}} filter {geoip{source=>"ip"}} output {stdout{codec=>rubydebug}}'
```
The error, using `--debug`:
```
The error reported is:
  can't convert nil into String
org/jruby/RubyFileTest.java:119:in `exist?'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.6/lib/logstash/filters/geoip.rb:66:in `register'
org/jruby/RubyArray.java:1613:in `each'
/opt/logstash/lib/logstash/pipeline.rb:151:in `start_filters'
/opt/logstash/lib/logstash/pipeline.rb:78:in `run'
/opt/logstash/lib/logstash/agent.rb:147:in `execute'
/opt/logstash/lib/logstash/runner.rb:124:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/lib/logstash/runner.rb:129:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12:in `initialize'
```
which indicates this is failing:
https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L66

**Comment by suyograo** [comment]
Looks like the vendor files are not downloaded - 
```
ubuntu@ip-10-0-1-11:/opt/logstash$ find . -name GeoLiteCity*
```

**Comment by jsvd** [comment]
At the moment we still rely on plugin gems shipping with vendor content inside of them vs downloaded at install. This issue is a result of a bad mass plugin publish last week, where I didn't include the intermediate "rake vendor" step before the publish task.
Executing a new round of publish for plugins that use vendor.json

**Comment by jsvd** [comment]
Republished:
* logstash-codec-collectd
* logstash-filter-geoip
* logstash-filter-useragent

After a clean git clone and "rake artifact:rpm":

```
% rpm -qpl build/logstash-2.0.0.dev-1.noarch.rpm| grep vendor/Geo
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.7/vendor/GeoIPASNum-2014-02-12.dat
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.7/vendor/GeoLiteCity-2013-01-18.dat
```

**Comment by suyograo** [comment]
Update the new gem. Looks good now
```
ubuntu@ip-10-0-1-11:~$ sudo /opt/logstash/bin/plugin list --verbose logstash-filter-geoip
logstash-filter-geoip (0.1.7)
ubuntu@ip-10-0-1-11:~$ cd /opt/logstash
ubuntu@ip-10-0-1-11:/opt/logstash$ find . -name GeoLiteCity*
./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.7/vendor/GeoLiteCity-2013-01-18.dat
```
