### ISSUE TITLE
rake vendor:gems fails after fresh clone

### ISSUE THREAD

**Issue by electrical** [elasticsearch/logstash#2746]
```
$ rake vendor:gems
Invoking bundler install...
Plugin not found, aborting
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
rake aborted!
Could not find gem 'logstash-core (>= 0) java' in source at ..
Source does not contain any versions of 'logstash-core (>= 0) java'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/resolver.rb:369:in `resolve'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/resolver.rb:167:in `start'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/resolver.rb:129:in `resolve'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/definition.rb:193:in `resolve'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/definition.rb:132:in `specs'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/definition.rb:121:in `resolve_remotely!'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/installer.rb:79:in `run'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/installer.rb:18:in `install'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/cli/install.rb:80:in `run'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/cli.rb:157:in `install'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/vendor/thor/command.rb:27:in `run'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/vendor/thor/base.rb:440:in `start'
/home/richard/projects/logstash/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.3/lib/bundler/cli.rb:10:in `start'
/home/richard/projects/logstash/logstash/lib/logstash/bundler.rb:67:in `invoke_bundler!'
org/jruby/RubyKernel.java:1507:in `loop'
/home/richard/projects/logstash/logstash/lib/logstash/bundler.rb:64:in `invoke_bundler!'
org/jruby/RubyProc.java:271:in `call'
/home/richard/projects/logstash/logstash/lib/logstash/bundler.rb:34:in `capture_stdout'
/home/richard/projects/logstash/logstash/lib/logstash/bundler.rb:63:in `invoke_bundler!'
/home/richard/projects/logstash/logstash/rakelib/vendor.rake:134:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => vendor:gems
(See full trace by running task with --trace)
```

**Comment by colinsurprenant** [comment]
is this still current? on OSX or Linux? in 1.5 branch or master?

**Comment by purbon** [comment]
I guess this error is shown in http://build-eu-00.elasticsearch.org/view/LS%201.5/job/Logstash_1.5_All_Plugins_test/209/console, so I'm pround to think this a bug.

**Comment by purbon** [comment]
running now on linux in a vm to see if I reproduce it, in jenkins is a linux box.

**Comment by purbon** [comment]
I just run:

```rake bootstrap```
```rake vendor:gems```

and then 

``` bin/plugin install logstash-output-elasticsearch````

 in a 

```Linux vagrant-ubuntu-trusty-64 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```


and everything went smooth without any error. I check also for the jars and they are there.

Opening another bug for the jenkins complain.

**Comment by ph** [comment]
I have the same issue on windows with the generated packages from @suyograo

**Comment by purbon** [comment]
@electrical @suyograo @ph can we close this now that we fix the bootstrap issue? is this related?

**Comment by ph** [comment]
Yes the changes in the `bootstrap` we did is fixing this issue.

**Comment by ph** [comment]
`rake bootstrap` will make sure you system ok on a fresh checkout.

**Comment by purbon** [comment]
+1 as it should be!
