### ISSUE TITLE
Problems when running the all plugins test

### ISSUE THREAD

**Issue by purbon** [elasticsearch/logstash#2756]
When running the all plugins test in jenkins, it shows this error:

```
websocket, logstash-output-zabbix, logstash-input-meetup, logstash-codec-es_bulk, logstash-output-elasticsearch-ec2, logstash-patterns-core, logstash-mixin-aws, logstash-input-couchdb_changes, logstash-filter-metaevent, logstash-filter-zeromq, logstash-codec-s3plain, logstash-codec-cloudfront, logstash-codec-gzip_lines, logstash-codec-avro, logstash-input-heartbeat, logstash-filter-tld, logstash-filter-oui
Installation successful
[plugin:install-development-dependencies] Installing development dependencies of all installed plugins
Installing logstash-devutils, logstash-codec-plain, jdbc-sqlite3, ftw, logstash-output-elasticsearch, stud, logstash-codec-multiline, logstash-input-generator, rumbster, logstash-filter-kv, logstash-filter-ruby, logstash-codec-json, logstash-input-stdin, logstash-codec-line
Installation successful
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/simplecov-0.9.2/lib/simplecov.rb:31 warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
Using Accessor#strict_set for specs
rake aborted!
LoadError: no such file to load -- logstash-output-elasticsearch_jars
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:11:in `(root)'
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/spec/outputs/elasticsearch_spec.rb:1:in `(root)'
/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/c
```

having shown up beforehand some other errors related to jars fetching

```
Extracting jruby-1.7.17/tool/nailgun/ng.exe from vendor/_/jruby-bin-1.7.17.tar.gz 755
Extracting jruby-1.7.17/tool/nailgun/README.txt from vendor/_/jruby-bin-1.7.17.tar.gz 644
Extracting jruby-1.7.17/tool/nailgun/src/c/ng.c from vendor/_/jruby-bin-1.7.17.tar.gz 644
Installing stud >= 0 because the build process needs it.
[bootstrap] Fetching and installing gem: stud (>= 0)
Successfully installed stud-0.0.19
1 gem installed
Installing bundler >= 1.3.5 because the build process needs it.
[bootstrap] Fetching and installing gem: bundler (>= 1.3.5)
Successfully installed bundler-1.8.3
1 gem installed
Invoking bundler install...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project rubygems:jruby-kafka:1.1.2 (/home/jenkins/workspace/Logstash_1.5_All_Plugins_test/vendor/bundle/jruby/1.9/specifications/jruby-kafka-1.1.2-java.gemspec) has 3 errors
[ERROR]     Unresolveable build extension: Plugin de.saumya.mojo:gem-extension: or one of its dependencies could not be resolved: Failure to find de.saumya.mojo:gem-extension:jar: in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: gem
[ERROR]     'build.plugins.plugin.version' for de.saumya.mojo:gem-maven-plugin must be a valid version but is ''.
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error Bundler::InstallError, retrying 1/10
Error Errno::EBADF, retrying 2/10
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project rubygems:logstash-input-log4j:0.1.3 
```

**Comment by suyograo** [comment]
I get the same error while building on ubuntu 14 as well;

```
 gem installed
Invoking bundler install...

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project rubygems:jruby-kafka:1.1.2 (/home/ubuntu/logstash/vendor/bundle/jruby/1.9/specifications/jruby-kafka-1.1.2-java.gemspec) has 3 errors
[ERROR]     Unresolveable build extension: Plugin de.saumya.mojo:gem-extension: or one of its dependencies could not be resolved: Could not find artifact de.saumya.mojo:gem-extension:jar: in central (http://repo.maven.apache.org/maven2) -> [Help 2]
[ERROR]     Unknown packaging: gem
[ERROR]     'build.plugins.plugin.version' for de.saumya.mojo:gem-maven-plugin must be a valid version but is ''.
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error Bundler::InstallError, retrying 1/10
Error Errno::EBADF, retrying 2/10
```

**Comment by suyograo** [comment]
master works
