### ISSUE TITLE
rake test:install-core aborts abruptly!

### ISSUE THREAD

**Issue by 91pavan** [elasticsearch/logstash#2759]
I'm trying to install logstash-filter-cidr plugin, but I just can't seem to get this working no matter what I do!

```
vagrant@vagrant-ubuntu-trusty-64:~/logstash-1.5.0.beta1$ bin/plugin install logstash-filter-cidr
validating logstash-filter-cidr >= 0
Valid logstash plugin. Continuing...
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: logstash-filter-cidr (= 0.1.5) requires logstash-core (< 2.0.0, >= 1.4.0)
           resolve_for at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:144
           resolve_for at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:194
               resolve at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:87
               resolve at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/request_set.rb:134
  resolve_dependencies at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:408
               install at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:345
               execute at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/pluginmanager/install.rb:60
                   run at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/command.rb:67
               execute at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11
                   run at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/runner.rb:144
                  call at org/jruby/RubyProc.java:271
                   run at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/runner.rb:171
                  call at org/jruby/RubyProc.java:271
            initialize at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/task.rb:12

```

Ok, let's install/upgrade core as per https://github.com/elasticsearch/logstash readme

```
rake test:install-core
```

Output:
```
vagrant@vagrant-ubuntu-trusty-64:~/logstash-1.5.0.beta1$ rake test:install-core --trace
** Invoke vendor:jruby (first_time)
** Execute vendor:jruby
** Invoke vendor/_/jruby-bin-1.7.16.tar.gz (first_time)
** Invoke vendor/_ (first_time, not_needed)
** Invoke vendor (first_time, not_needed)
** Execute vendor/_/jruby-bin-1.7.16.tar.gz
** Invoke vendor/jruby (first_time, not_needed)
** Invoke vendor (not_needed)
** Invoke dependency:archive-tar-minitar (first_time)
** Execute dependency:archive-tar-minitar
** Invoke gem:require (first_time)
** Execute gem:require
rake aborted!
Don't know how to build task 'test:install-core'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/task_manager.rb:49:in `[]'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:148:in `invoke_task'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:106:in `top_level'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:115:in `run_with_threads'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:100:in `top_level'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:78:in `run'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:165:in `standard_exception_handling'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rake/application.rb:75:in `run'
/home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/gems/shared/gems/rake-10.1.0/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
vendor/jruby/bin/rake:23:in `(root)'
```
Even rake boostrap doesn't work

```
vagrant@vagrant-ubuntu-trusty-64:~/logstash-1.5.0.beta1$ rake bootstrap
Downloading https://download.elasticsearch.org/kibana/kibana/kibana-3.1.2.tar.gz
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound
/home/vagrant/logstash-1.5.0.beta1/tools/Gemfile not found
--> Retrying vendor:gems upon exception=Bundler::GemfileNotFound

```

Is there some step which I've missed?

**Comment by purbon** [comment]
@91pavan this are code changes introduced in master and 1.5 branches. Also last plugin versions are not intended to work well with beta1, so you're not able to install them.

you've one option here:

* Can you get the code and build directly from the git repo? then you will be able to install the last plugin versions.
* Can you install a previous version, for example for logstash-filter-cidr is going to be 0.1.4. You can do that by passing ```--version '0.1.4'``` to the install command.

Is this working for you?

**Comment by 91pavan** [comment]
@purbon Thank you Pere. The first option worked, second option complained that there were too many arguments passed to the command. I'll close this issue myself.

**Comment by purbon** [comment]
Awesome, happy to help!
